[tools]
rotrieve = { source = "roblox/rotriever", version = "0.5.1" }
rojo = { source = "Roblox/rojo-rbx-rojo", version = "7.0.0" }
selene = { source = "Roblox/Kampfkarren-selene", version = "0.25.0" }
stylua = { source = "Roblox/JohnnyMorganz-StyLua", version = "0.18.1" }
testez = { source = "roblox/testez", version = "0.3.2" }
rbx-aged-cli = { source = "Roblox/rbx-aged-tool", version = "=5.8.0" }
