[package]
name = "GraphqlTag"
version = "2.12.4"
author = "Roblox"
content_root = "src"

[dependencies]
GraphQL = {git="https://github.com/Roblox/graphql-lua", rev = "master"}

[dev_dependencies]
JestRoblox = "github.com/roblox/jest-roblox@2.0.0-pre.0"
LuauPolyfill = "github.com/roblox/luau-polyfill@0.2.0"
