[package]
name = "GraphqlTag"
version = "2.12.4"
author = "Roblox"
content_root = "src"

[dependencies]
GraphQL = { git = "https://github.com/Roblox/graphql-lua", rev = "master" }
LuauPolyfill = "github.com/roblox/luau-polyfill@=0.2.6"

[dev_dependencies]
JestGlobals = "github.com/roblox/jest-roblox@=2.3.0"
